server:
  port: 8080

spring:
  application:
    name: gateway-proxy

zuul:
  prefix: /api
  ignoredServices: '*'
  routes:
    agent-service:
      path: /agent/**
      serviceId: agent-service
      stripPrefix: false
    test-service:
        path: /test/**
        serviceId: test-service
        stripPrefix: false

hystrix:
  command:
    agent-service:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000
    test-service:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000


management:
  endpoints:
    web:
      exposure:
        include:
          - '*'



eureka:
  client:
    service-url:
      defaultZone: http://localhost:9001/eureka